name: Deploy medical

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy Server
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}

          script: |
            echo "STEP 1"
            cd ${{ secrets.PROJECT_PATH }}

            echo "STEP 2"
            git pull origin main

            echo "STEP 3"
            npm install

            echo "STEP 4"
            npm run build

            echo "STEP 5"
            pm2 restart medical-project

            echo "STEP 6"
            pm2 save

            echo "STEP 7"

            echo "DONE"

            exit 0